rock:
  node_listen: 9080
  enable_heartbeat: false
  enable_admin: true

mysql:
  host: ""
  port: 3306
  user: ""
  password: ""
  database: "rock"
  timeout: 3000 # ms
  max_idle_timeout: 30000
  pool_size: 50

redis:
  host: "127.0.0.1"
  port: 6379
  timeout: 3000 # ms
  max_idle_timeout: 30000
  pool_size: 50

plugins:                          # plugin list
  - name: limit-req
    disabled: true
    scope: router
  - name: limit-distribution
    disabled: true
    scope: router
  - basic-auth:
    disabled: false
    scope: global
  - name: jwt-auth
    disabled: false
    scope: global
  - name: redirect
    disabled: false
    scope: global